### ISSUE TITLE
Failures reading data in 7.49-0.el7 (stable)

### ISSUE THREAD

**Issue by oasunta** [MDSplus/mdsplus#1519]
I'll start by apologizing that this explanation is rather lengthy. It's because I wanted to try to test as much as I could to narrow down the problem (I'm not sure how well that worked out in the end, though...). 

We have a problem in 7.49.-0 with nodes that used to work in 7.7.-4. For testing, take two nodes:

(1)
TDI> mag.rog.mct:i
Build_With_Units(Build_Param(Build_Signal(.MAG.ROG.MCT:I_GAIN * (GETNCI(FIND_ANALOGUE_SIGNAL("I_ROG_MCT", "ain"), "record") - .MAG.ROG.MCT:I_DRIFT * (DIM_OF(GETNCI(FIND_ANALOGUE_SIGNAL("I_ROG_MCT", "ain"), "record")) - .002) - .MAG.ROG.MCT:I_OFFSET), *, DIM_OF(GETNCI(FIND_ANALOGUE_SIGNAL("I_ROG_MCT", "ain"), "record"))), "CURRENT IN THE TOP MC COIL AND CASE", *), "A")

(2)
TDI> psu.bvl:i
Build_With_Units(Build_Param(21810.3 * COMPILE(find_analogue_signal("I_BVL_PSU", "ain")) / 10., "PSU current", *), "A")

I can always read the TDI strings that are stored in the nodes. The problem arises when trying to retrieve data(). Both nodes call find_analogue_signal(), a function that simply finds the name of the node where the raw data is, but the rest is just references to other nodes in the tree and standard TDI.

In TDI, if I read data in node (1) first, everything works:

TDI> treeopen('st40',5157);
TDI> data(mag.rog.mct:i)
Set_Range(211000,-50.98459301688293D0 /*** etc. ***/)
TDI> data(psu.bvl:i)
Set_Range(211000,44.7968 /*** etc. ***/)

If I try to read node (2) first, TDI freezes.

TDI> treeopen('st40',5157);
TDI> data(psu.bvl:i)
^C

The fact that getting data from (2) works after getting data from (1), but not before, makes it look as if the TDI function would somehow have a memory.

I also thought that maybe COMPILE(find_analogue_signal("I_BVL_PSU", "ain")) could be the problem because that was one of the differences between the nodes. If I execute the external function call on its own first, the COMPILE() works.

TDI> treeopen('st40',5157);
TDI> find_analogue_signal("I_BVL_PSU", "ain")
"\\TEPCS::TOP.ACQ2106_033:CH006"
TDI> COMPILE(find_analogue_signal("I_BVL_PSU", "ain"))
.TEPCS.ACQ2106_033:CH006

But when run:
TDI> treeopen('st40',5157);
TDI> compile(find_analogue_signal("I_BVL_PSU", "ain"))
^C

TDI freezes.

In Python, using the Tree object, if I evaluate node (1) first, I get an error message from the second node:

In [8]: t  = Tree('st40',5157)
In [9]: t.getNode('mag.rog.mct:i').data()
Out[9]: 
array([  -50.98459302,   167.72563986,   167.78505486, ...,
       12704.05366115, 12485.46225828, 12267.53747376])

In [10]: t.getNode('psu.bvl:i').data()

---------------------------------------------------------------------------
TdiUNKNOWN_VAR                            Traceback (most recent call last)
<ipython-input-10-8b24bb978aba> in <module>()
----> 1 t.getNode('psu.bvl:i').data()

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/tree.pyc in data(self, *altvalue)
   1526 
   1527     def data(self,*altvalue):
-> 1528         return self.record.data(*altvalue)
   1529 
   1530     @property

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in data(self, *altvalue)
    521         """
    522         try:
--> 523             data = _cmp.DATA(self)._setTree(self.tree).evaluate()
    524             return data.value if isinstance(data,Data) else data
    525         except _exc.TreeNODATA:

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in evaluate(self, **kwargs)
    469         @rtype: Data
    470         """
--> 471         return TdiEvaluate(self,**kwargs)
    472 
    473 

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in TdiEvaluate(expression, **kwargs)
     94 def TdiEvaluate(expression,**kwargs):
     95     """Evaluate and functions. Format: TdiEvaluate(data)"""
---> 96     return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)
     97 
     98 def TdiData(expression,**kwargs):

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in _TdiShrFun(function, errormessage, expression, *args, **kwargs)
     75     _tre._TreeCtx.pushTree(tree)
     76     try:
---> 77         _exc.checkStatus(function(*rargs))
     78     finally:
     79         _tre._TreeCtx.popTree()

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsExceptions.pyc in checkStatus(status, ignore)
     88             print(exception.message)
     89         else:
---> 90             raise MDSplusException(status)
     91 
     92 ########################### generated from mitdevices_messages.xml ########################

TdiUNKNOWN_VAR: %TDI-E-UNKNOWN_VAR, Unknown/undefined variable name

If I go straight to the problematic node (2), iPython freezes:

In [2]: t = Tree('st40',5157)

In [3]: t.getNode('psu.bvl:i').getData()
Out[3]: Build_With_Units(Build_Param(21810.3 * COMPILE(find_analogue_signal("I_BVL_PSU", "ain")) / 10., "PSU current", *), "A")

In [4]: t.getNode('psu.bvl:i').data()
^C

The same happens if I query the nodes through the Connection object. Something else first:
In [2]: conn  = Connection('192.168.1.7')
In [3]: conn.openTree('st40',5157)

In [4]: conn.get('mag.BPPROBE.P518:DBDT').data()
Out[4]: 
array([0.7853851 , 0.34335357, 0.5643693 , ..., 0.63811755, 0.34335357,
       0.5643693 ], dtype=float32)

In [5]: conn.get('psu.bvl:i').getData()
Out[5]: Set_Range(211000,44.7968 /*** etc. ***/)

In [6]: conn.get('psu.bvl:i').data()
Out[6]: 
array([44.796795 , 40.02529  , 48.203823 , ..., 18.90089  , 22.988075 ,
       14.8116255], dtype=float32)

The problematic node first:
In [2]: conn  = Connection('192.168.1.7')
In [3]: conn.openTree('st40',5157)
In [4]: conn.get('psu.bvl:i').data()
^C

Also the MATLAB interface behaves in the same way.

In an attempt to see if COMPILE() is indeed the problem, I replaced the Data.compile( ...COMPILE(find_analogue_signal("nodename") ) with tree.tdiCompile( ...GETNCI(find_analogue_signal("nodename"),"record") ) 
in putData(), that seems to have helped, for TDIC (because now it evaluates the content of the node):
TDI> treeopen('st40',301);
TDI> psu.bvl:i
Build_Signal(Build_With_Units(Set_Range(211000,44.7968 /*** etc. ***/), "V"), *, Build_Dim(Build_Window(0, 211000 - 0 - 1, Build_With_Units(0 * (1 * 10D-6), "s")), Build_With_Units(0 * (1 * 10D-6) : (211000 - 1) * (1 * 10D-6) : 1 * 10D-6, "s")))
TDI> data(psu.bvl:i)
Set_Range(211000,44.7968 /*** etc. ***/)
TDI> 

The improvement might be because TDI now evaluates the node content "earlier" (compare the above to the below):
In [2]: t  = Tree('st40',301)
In [3]: t.getNode('psu.bvl:i').getData()
Out[3]: 21810.3 * GETNCI(find_analogue_signal("I_BVL_PSU", "ain"), "record") / 10.

This 'fix' also solves the issue for MATLAB. However, even if I looped over all the trees from our earlier experimental campaign to modify the contents of the affected nodes and applied the fix above (which I don't really want to do unless I have to), it looks like I'd still have the problem (at least) in Python. Without the COMPILE() I just get a different error message:

In [2]: t  = Tree('st40',301)

In [3]: t.getNode('psu.bvl:i').getData()
Out[3]: 21810.3 * GETNCI(find_analogue_signal("I_BVL_PSU", "ain"), "record") / 10.

In [4]: t.getNode('psu.bvl:V').getData()
Out[4]: Build_With_Units(Build_Param(1636.91 * COMPILE(find_analogue_signal("U_BVL_PSU", "ain")) / 10., "PSU voltage", *), "V")

In [5]: t.getNode('psu.bvl:i').data()

---------------------------------------------------------------------------
TreeNOT_OPEN                              Traceback (most recent call last)
<ipython-input-5-8b24bb978aba> in <module>()
----> 1 t.getNode('psu.bvl:i').data()

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/tree.pyc in data(self, *altvalue)
   1526 
   1527     def data(self,*altvalue):
-> 1528         return self.record.data(*altvalue)
   1529 
   1530     @property

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in data(self, *altvalue)
    521         """
    522         try:
--> 523             data = _cmp.DATA(self)._setTree(self.tree).evaluate()
    524             return data.value if isinstance(data,Data) else data
    525         except _exc.TreeNODATA:

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in evaluate(self, **kwargs)
    469         @rtype: Data
    470         """
--> 471         return TdiEvaluate(self,**kwargs)
    472 
    473 

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in TdiEvaluate(expression, **kwargs)
     94 def TdiEvaluate(expression,**kwargs):
     95     """Evaluate and functions. Format: TdiEvaluate(data)"""
---> 96     return _TdiShrFun(_TdiShr.TdiEvaluate,"Error evaluating",expression,**kwargs)
     97 
     98 def TdiData(expression,**kwargs):

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsdata.pyc in _TdiShrFun(function, errormessage, expression, *args, **kwargs)
     75     _tre._TreeCtx.pushTree(tree)
     76     try:
---> 77         _exc.checkStatus(function(*rargs))
     78     finally:
     79         _tre._TreeCtx.popTree()

/usr/lib/python2.7/site-packages/mdsplus-7.49.0-py2.7.egg/MDSplus/mdsExceptions.pyc in checkStatus(status, ignore)
     88             print(exception.message)
     89         else:
---> 90             raise MDSplusException(status)
     91 
     92 ########################### generated from mitdevices_messages.xml ########################

TreeNOT_OPEN: %TREE-W-NOT_OPEN, Tree not currently open

There are links between trees, but they are similar in the nodes that work and the nodes that don't.

Does anyone have any ideas what could have changed between 7.7.-4 and 7.49.-0 to cause this problem?

**Comment by tfredian** [comment]
I just started looking into this problem this morning. I suspect this might have been caused by extensive changes in the MDSplus code attempting to fix many race conditions which could occur in multi-threaded applications doing MDSplus operations. We will try to replicate this problem and see if there is a workaround that would not require you to change all your existing stored expression.

I think the main problem might be your use of compile() in expressions. Since you are trying to change the node path from a string into a node reference you might try using build_path() instead. Let us know if that fixes things as it will provide us with more clues as to what is happening.

**Comment by oasunta** [comment]
Thank you for looking into this. Replacing the COMPILE( ) with BUILD_PATH( ) results in the same behaviour as replacing COMPILE( ) with GETNCI(...,"record"):
(1) TDI and MATLAB work
(2) Python using the Tree object returns the "TreeNOT_OPEN: %TREE-W-NOT_OPEN, Tree not currently open" error, as shown in above.
(3) Python using the Connection object works.

**Comment by tfredian** [comment]
Hi Otto,

We have been able to reproduce the problems you were running into and are attempting to find fixes for the problems. Here are some of the things we have found.
I am surprised that the compile(find_analogue_signal()) approach ever worked unless the find_analogue() function was invoked at some point prior accessing the data produced by the node containing that expression. The compile() function is not reentrant because it was implemented using older lex and yacc tools which used static variables. We added locking to prevent threaded applications from trying to compile tdi concurrently but in your case the locking is causing a deadlock. That deadlock will not occur if you invoke find_analoque_signal once prior to accessing the data since tdi will compile and load the function and not have to do it while a compile is in progress. We are looking into the possibility of making the compile operation reentrant but that is not simple.

Second, the python problem is indeed a tree ctx problem. Since the MDSplus python interface enables applications to have several Tree instances with different trees being opened the execution of tdi expressions is complicated when the expressions contain tree references. This tree ctx handling has been modified several times for dealing with both multithreaded applications and simple applications which use multiple Tree instances. Unfortunately we were looking through the data objects used in an expression being evaluated to detect node or tree references (i.e. containing TreeNode instances or TreePath instances) and properly handle the tree ctx. However since your expression is converting strings to tree references the tree ctx handling is not done properly. We will be exploring the possibility of attaching a tree reference to any data read from a node and using the correct tree ctx when evaluating the contents of the node.

This may take a while to fix... sorry.

**Comment by zack-vii** [comment]
fixed by #1522

**Comment by oasunta** [comment]
Thank you for fixing the problems so quickly! When can I expect the fixes to be available in a stable release? 

I tested the current alpha release (alpha-7.61-3.el7) and, in Python, I still get the same errors [freezing] for the old nodes with COMPILE() in them when using Tree [Connection] object. Everything seems to work in TDI, though. I'm hesitant to start using the alpha version in a production environment anyway, hence the question about a stable release.

**Comment by zack-vii** [comment]
We need to add this to stable, but before we do, when you say you still get the dead lock [freezing] when using Tree [Connection] are you using the Tree object or the Connection object. The former should be ok now or we missed something, the latter might be because the thin client commands are executed on the server that is still running the broken stable i assume. Is that the case?

**Comment by oasunta** [comment]
I was testing both Tree object and Connection object. However, you are correct that, when I tested the Connection object, I accidentally connected to the server that is running the broken stable release. Connecting to my test server (running the alpha release), the Connection object works properly. Just like TDI.

I’m still having problems with the Tree object, though. If I read the problematic node first I get:
TreeNOT_OPEN: %TREE-W-NOT_OPEN, Tree not currently open

Whereas if I read something else calling find_analogue_signal() first, I get:
TdiUNKOWN_VAR: %TDI-E-UNKNOWN_VAR, Unknown/undefined variable name

**Comment by zack-vii** [comment]
I will have another look at the TreeNotOpen problem, calling  find_analogue_signal() raising TdiUNKOWN_VAR can have multiple reasons. could you post the file content (function definition) of find_analogue_signal please. you can locate the file using the tdi command 
```tdi
help("find_analogue_signal")
```
How do we want to fix the ctx problem of the python api in stable (once completely solved)? We could  cherry-pick (rocky road, as the root of the problem might lie somewhere else for stable) or promote the api from alpha (might be break other things).

**Comment by zack-vii** [comment]
i think i found the problem withthe TreeNotOpen.. i might be able to squeeze in a hot fix for alpha befor the next release.. for stable we will have to see

**Comment by oasunta** [comment]
Great! Just in case you still need it, below please find the find_analogue_signal.fun function. I apologize in advance for the messiness of the code… :-S It's grown organically and, currently, it is only tested and used for analogue input signals with IOtype="ain".

    /* FIND_ANALOGUE_SIGNAL.FUN
       A function to find the signal matching the given name.

       Usage:
       FIND_ANALOGUE_SIGNAL('name','IOtype')

       Author: O. Asunta
       Date  : 04-2018

    */
    PUBLIC FUN FIND_ANALOGUE_SIGNAL(IN _name, IN _IOtype) {

    /* Select which list to go through based on the type of signal */
    /*  IF (INDEX(_IOtype,"aout")==0) {_l=data(pss.ao.list);  }
      IF (INDEX(_IOtype,"ain")==0)  {_l=data(pss.ai.list);  }
      IF (INDEX(_IOtype,"dinout")==0)  {_l=data(pss.dio.list); }
    */

    /* Load the lists of names -- make sure it works even if _l2 doesn't exist*/
      if_error(_l1= data(pss.ai:list),_l1=[]);
      if_error(_l1= data(pss.ai:list),_l1=[]);
      if_error(_l2= data(raw_mag.acq2106_034:list),_l2=[]);
      if_error(_l2= data(raw_mag.acq2106_034:list),_l2=[]);
      if_error(_l3= data(raw_mag.acq1001_185:list),_l3=[]);
      if_error(_l3= data(raw_mag.acq1001_185:list),_l3=[]);


    /* Loop over the lists of names. Store the index '_ind' and break if
    the name is found. */

      FOR (_J=0; _J<size(_l1); _J++ ) {
	  IF (INDEX(_l1[_j],_name) == 0) {
	    IF (INDEX(trim(_name),trim(_l1[_j])) == 0) {
	      _ind = _j; _tree="pcs"; BREAK;
	    }
	  }
      }
      FOR (_J=0; _J<size(_l2); _J++ ) {
	  IF (INDEX(_l2[_j],_name) == 0) {
	    IF (INDEX(trim(_name),trim(_l2[_j])) == 0) {
	   _ind = _j; _tree="mag1"; BREAK;
	    }
	  }
      }
      FOR (_J=0; _J<size(_l3); _J++ ) {
	  IF (INDEX(_l3[_j],_name) == 0) {
	    IF (INDEX(trim(_name),trim(_l3[_j])) == 0) {
	   _ind = _j; _tree="mag2"; BREAK;
	    }
	  }
      }

    /*      WRITE(*,_j); */


      /* If the name was not found, return -1 */
      IF (_J=size(_l1)) _ind=-1;

    /* Build the node name */ 

    /* Indexing start from zero */
      _channel = _ind + 1; 


    /*  WRITE(*,"channel=");
      WRITE(*,_channel);
    */  

      IF (INDEX(_IOtype,"ain")==0)  { 
	IF(INDEX("pcs",_tree) == 0) {
	  IF(_channel > value_of(pss.ai.nin1)  ) {
	    _channel = _channel-int(value_of(pss.ai.nin1),kind(1));
	    _node=concat( "\\TEPCS::TOP.ACQ2106_033:CH",iii(_channel) );
	  } ELSE {
	    _node=concat( "\\TEPCS::TOP.ACQ2106_032:CH",iii(_channel) );
	  }
	} ELSE {
	  IF(INDEX("mag1",_tree) == 0) {
	    _node=concat( "\\RAW_MAG::TOP.ACQ2106_034:CH",iii(_channel) );
	  } ELSE {
	    IF(INDEX("mag2",_tree) == 0) {
	      _node=concat( "\\RAW_MAG::TOP.ACQ1001_185:CH",iii(_channel) );
	    }
	  }
	}
      }


      IF (INDEX(_IOtype,"aout")==0) { 
	_node=concat(_treepath,"3.AO:CH",iii(_channel)); 
      }


      IF (INDEX(_IOtype,"dinout")==0) {
	SWITCH(_channel) {
	CASE(1:16)  _node=get_bit( TEPCS.ACQ2106_032.DO32,_channel-1 ); BREAK;
	CASE(17:32) _node=get_bit( TEPCS.ACQ2106_032.DI32,_channel-1 ); BREAK;
	CASE(33:48) _node=get_bit( TEPCS.ACQ2106_033.DI32,_channel-32-1 ); BREAK;
	CASE(49:64) _node=get_bit( TEPCS.ACQ2106_033.DO32,_channel-32-1 ); BREAK;
	CASE DEFAULT BREAK;
	}
      }

      RETURN(_node);
    }

Some oddities ( e.g., the double calls to if_error() ) are due to strange issues that needed a quick workaround, some just bad programming.

**Comment by zack-vii** [comment]
Does it work now on alpha 7.61.4?

**Comment by oasunta** [comment]
Yes, it does! Thank you.

How do I know which stable version eventually includes the changes that fixed this Issue?

**Comment by zack-vii** [comment]
Stay tuned, ;)
No but seriously, we will keep this issue open until its solved for stable. The PR that will fix it will ideally reference this issue and well, we will probably ask you to confirm that this is actually true.
Since there has been quite a few changes been made between alpha and stable it is basically a new quest with some hints what to look for. It might take a bit but I will look into it some more starting today.

**Comment by oasunta** [comment]
OK. Sounds good.

**Comment by zack-vii** [comment]
@oasunta : the new stable version it building just now and should finish any minute. Could you check it this fixes the remaining issues.

**Comment by zack-vii** [comment]
Should be fixed as of version stable 7.49.3

**Comment by oasunta** [comment]
@zack-vii : Yes, I can confirm that I don't get this problem using stable 7.49.3. 

Thank you!
